### ISSUE TITLE
ProcFlags uint -> ulong?

### ISSUE THREAD

**Issue by alishahb** [MechanicalPriest/SimcProfileParser#97]
SimcRawSpell -> ProcFlags uint - seems to be wrong type, should be ulong possibly

as for https://www.wowhead.com/spell=199471/soul-flame
the value from rawdata is 137439285588  which is bigger than max uint can hold

do you have discord or maybe email how to contact you ?

**Comment by Niphyr** [comment]
Thanks @alishahb it looks like you're correct on the datatype. You can contact me on discord at `niphyr`.
